DATA: 'hmdb51'
SIZE: 112
MM_ROOT: './mmaction2'
SYN_PATH: 'rded/exp/hmdb51-ipc1-rded/syn_data'
WANDB_NAME: 'ipc1-soft-rded'
Inter: 'none'
IPC: 1
FACTOR: 1
MAX_SCALE_CROPS: 1

TRAIN_LOADER:
    batch_size: 10
    shuffle: True
    num_workers: 4
    pin_memory: True

VAL_LOADER:
    batch_size: 100
    shuffle: False
    num_workers: 4
    pin_memory: True

# TEACHER:
#     config: 'mmaction2/configs/recognition/conv3/conv3-kinetics-8x56x56.py'
#     checkpoint: 'mmaction2/work_dirs/conv3-kinetics-8x56x56/best_acc_top1_epoch_70.pth'

# STUDENT:
#     config: 'mmaction2/configs/recognition/conv3/conv3-kinetics-8x56x56.py'

TEACHER:
    config: 'mmaction2/configs/recognition/conv3/conv3-hmdb51-8x112x112.py'
    checkpoint: 'mmaction2/work_dirs/conv3-hmdb51-8x112x112/best_acc_top1_epoch_130.pth'

STUDENT:
    config: 'mmaction2/configs/recognition/conv3/conv3-hmdb51-8x112x112.py'

OPTIMIZER: 'Adam' # ['SGD', 'Adam']
SGD:
    lr: 0.02 # 
    momentum: 0.9
    weight_decay: 0.0001

Adam:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.01

SCHEDULER: 'cosine' # ['warm-step', 'cosine', 'linear']
VAL_EPOCH: 300
WARMUP:
    start_factor: 0.1
    end_factor: 1
    total_iters: 10

MULTISTEPLR:
    milestones: [90, 130]
    gamma: 0.1
    
TRAIN_CONFIG:
    criterion: 'mse_gt' # ['kl', 'ce', 'mse_gt']
    mix_type: 'None' # ["mixup", "cutmix", "None"]
    lam: 1.0 # 0.8 for mixup
    temperature: 1
    label_method: 'soft'
